version: "3.9"

# creating the services that are part of our
# application stack
services:
  art-intersection:
    build: app/
    volumes:
      - ./app:/usr/src/app
      - ./secrets:/secrets
    ports:
      - 9000:4000
  db:
      image: mysql:8
      ports:
        - 3306:3306
      volumes:
        - ./db_bootstrap:/docker-entrypoint-initdb.d:ro
      environment:
        MYSQL_USER: webapp
        MYSQL_PASSWORD_FILE: /run/secrets/secret_db_pw
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/secret_db_root_pw
      secrets:
        - secret_db_pw
        - secret_db_root_pw

secrets:
  secret_db_pw:
    file: ./secrets/db_password.txt
  secret_db_root_pw:
    file: ./secrets/db_root_password.txt
